# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'file.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfile.proto\"<\n\x11UploadFileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x14\n\x0c\x66ile_content\x18\x02 \x01(\x0c\"%\n\x12UploadFileResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"#\n\x0eGetFileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"\'\n\x0fGetFileResponse\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\x32r\n\x0b\x46ileService\x12\x35\n\nUploadFile\x12\x12.UploadFileRequest\x1a\x13.UploadFileResponse\x12,\n\x07GetFile\x12\x0f.GetFileRequest\x1a\x10.GetFileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADFILEREQUEST']._serialized_start=14
  _globals['_UPLOADFILEREQUEST']._serialized_end=74
  _globals['_UPLOADFILERESPONSE']._serialized_start=76
  _globals['_UPLOADFILERESPONSE']._serialized_end=113
  _globals['_GETFILEREQUEST']._serialized_start=115
  _globals['_GETFILEREQUEST']._serialized_end=150
  _globals['_GETFILERESPONSE']._serialized_start=152
  _globals['_GETFILERESPONSE']._serialized_end=191
  _globals['_FILESERVICE']._serialized_start=193
  _globals['_FILESERVICE']._serialized_end=307
# @@protoc_insertion_point(module_scope)
